# Generated by Django 5.1.3 on 2024-11-27 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffm', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomesource', models.CharField(max_length=50)),
                ('income', models.IntegerField()),
                ('date', models.CharField(max_length=20)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ffm.user_register')),
            ],
        ),
    ]
