# Generated by Django 5.1.3 on 2024-11-27 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffm', '0003_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expensecategory', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('date', models.CharField(max_length=30)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ffm.user_register')),
            ],
        ),
    ]
