# Generated by Django 5.1.3 on 2024-11-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffm', '0004_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
