# Generated by Django 5.1.3 on 2024-11-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffm', '0005_income_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(),
        ),
    ]
