# Generated by Django 5.1.3 on 2024-11-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffm', '0006_alter_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
    ]
