# Generated by Django 5.1.3 on 2024-11-28 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffm', '0007_alter_expense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenseimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='expense/')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ffm.user_register')),
            ],
        ),
    ]
