# Generated by Django 5.1.3 on 2024-11-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffm', '0008_expenseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_register',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
