# Generated by Django 5.1.3 on 2024-12-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffm', '0009_user_register_code_expiration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='income',
            new_name='totalincome',
        ),
        migrations.RemoveField(
            model_name='user_register',
            name='code_expiration',
        ),
        migrations.RemoveField(
            model_name='user_register',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='income',
            name='yourincome',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
