# Generated by Django 5.1.3 on 2024-12-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffm', '0010_rename_income_income_totalincome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='totalincome',
            new_name='income',
        ),
    ]
