# Generated by Django 5.1.3 on 2024-12-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffm', '0011_rename_totalincome_income_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='yourincome',
            new_name='totalincome',
        ),
    ]
