# Generated by Django 5.0.1 on 2025-01-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffm', '0013_alter_expense_amount_alter_expense_expensecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffm.user_register')),
            ],
        ),
    ]
