# Generated by Django 5.0.1 on 2025-01-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffm', '0014_expenselimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselimit',
            name='expensecategory',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenselimit',
            name='limit_amount',
            field=models.FloatField(),
        ),
    ]
